user:
 attrs: [username, password, avatar]
room:
 attrs: [state]
 links:
  current: video
  owner: user
  userlist: userlist
  modlist: userlist
  mutelist: userlist
  playlist: videolist
  queue: videolist
video:
 attrs: [duration, vidid, title, uploader, thumb]
