user:
 attrs:
  username: String
  password: String
  avatar: String
room:
 links:
  current: video
  owner: user
  userlist: userlist
  modlist: userlist
  mutelist: userlist
  playlist: videolist
  queue: videolist
video:
 attrs: 
  duration: Number
  vidid: String
  title: String
  uploader: String
  thumb: String