// Generated by CoffeeScript 1.4.0
(function() {
  var roomid, socket;

  socket = io.connect('http://localhost:8081/');

  /*
  ask server for join request
  server replies with cached data
  ask for data as you go along using the save / load functions
  */


  roomid = get_roomid(window.location.pathname);

  socket.emit('join', {
    roomid: roomid,
    cookie: get_cookie('session')
  });

  socket.on('joined', function(res) {
    var id, obj, _ref, _results;
    document.cookie = 'session=' + res.cookie;
    _ref = res.cache;
    _results = [];
    for (id in _ref) {
      obj = _ref[id];
      _results.push(window.cache[id] = new models[obj.type](obj.attrs));
    }
    return _results;
  });

}).call(this);
