// Generated by CoffeeScript 1.4.0
(function() {
  var get_room_id, rid;

  window.api = {};

  window.socket = io.connect('http://localhost:8081');

  socket.on('session', function(session) {
    return document.cookie = 'session=' + session;
  });

  socket.on('state', function(state) {
    return console.log(state);
  });

  socket.on('userlist', function(info) {
    return console.log(info);
  });

  socket.on('playlist', function(info) {
    return console.log(info);
  });

  socket.on('obj', function(info) {
    var obj;
    if (cache[info.id]) {
      return cache[info.id].load(info);
    } else {
      obj = new models[info.type];
      obj.load(info);
      return cache[info.id] = obj;
    }
  });

  socket.on('message', function(state) {
    var msg;
    msg = new views.message({
      user: state.user,
      text: state.message
    });
    return $('#messages').append(msg.el);
  });

  get_room_id = function() {
    var idx, path;
    path = window.location.pathname;
    idx = path.indexOf('/r/');
    if (idx < 0) {
      return;
    }
    return path.substring(idx + 3, path.length);
  };

  rid = get_room_id();

  socket.emit('subscribe', {
    roomid: rid
  });

  api.message = function(msg) {
    return socket.emit('message', {
      roomid: rid,
      message: msg
    });
  };

  api.query = function(id) {
    return socket.emit('query', {
      id: id
    });
  };

}).call(this);
