// Generated by CoffeeScript 1.4.0
(function() {

  _.templateSettings = {
    interpolate: /\[\[(.+?)\]\]/g
  };

  window.main = function() {
    return $('input#chat').keyup(function(event) {
      var msg, prev;
      if (event.keyCode === 13) {
        msg = $(this).val();
        api.message(msg);
        window.lastmsg = msg;
        $(this).val('');
      }
      if (event.keyCode === 38 || event.keyCode === 40) {
        prev = $(this).val();
        $(this).val(window.lastmsg);
        return window.lastmsg = prev;
      }
    });
  };

}).call(this);
