// Generated by CoffeeScript 1.4.0
(function() {

  window.socket = io.connect('http://localhost:8081');

  socket.on('session', function(session) {
    return document.cookie = 'session=' + session;
  });

  socket.on('state', function(state) {
    return console.log(state);
  });

  socket.on('userlist', function(info) {
    return console.log(info);
  });

  socket.on('playlist', function(info) {
    return console.log(info);
  });

  socket.on('obj', function(info) {
    return console.log(info);
  });

}).call(this);
