// Generated by CoffeeScript 1.4.0
(function() {

  $('document').ready(function() {
    $.get('/res/schema.yaml', function(info) {
      var classname, schema, schemas;
      schemas = jsyaml.load(info);
      window.models = {};
      for (classname in schemas) {
        schema = schemas[classname];
        models[classname] = genclass(classname, schema.attrs, schema.links);
        models[classname + 'list'] = gencol(classname, models[classname]);
      }
      return window.main();
    });
    return window.lookup = function(id, type) {
      var obj;
      if (cache[id]) {
        return cache[id];
      }
      obj = new models[type];
      obj.id = id;
      cache[id] = obj;
      api.query(obj.id);
      return obj;
    };
  });

}).call(this);
