// Generated by CoffeeScript 1.4.0
(function() {

  window.views = {
    message: function(info) {
      var self;
      window.msg = this;
      this.user = lookup(info.user, 'user');
      this.temp = _.template($('script#message').html());
      self = this;
      this.user.bind('changed', function() {
        return self.render();
      });
      this.render = function() {
        var inner;
        inner = self.temp({
          username: self.user.get('username'),
          content: info.text
        });
        return self.el.html($(inner));
      };
      this.el = $(this.temp({
        username: self.user.get('username'),
        content: info.text
      }));
      return this;
    }
  };

}).call(this);
