// Generated by CoffeeScript 1.4.0
(function() {
  var events, io, readline;

  events = {};

  readline = require('readline').createInterface({
    input: process.stdin,
    output: process.stdout
  });

  readline.on('line', function(input) {
    var cmd, inputs, param;
    inputs = input.split(' ');
    cmd = inputs[0];
    param = inputs[1];
    if (events[cmd]) {
      return events[cmd](param);
    }
  });

  io = {
    bind: function(event, fn) {
      return events[event] = fn;
    },
    print: function(str) {
      return console.log(str);
    }
  };

  io.bind('clear', function() {
    return console.log('\033[2J');
  });

  io.bind('dump', function() {
    return module.exports.sparkle.dump();
  });

  io.bind('exec', function(cmd) {
    try {
      return io.print(eval(cmd));
    } catch (error) {
      return io.print(error);
    }
  });

  module.exports = {
    sparkle: null
  };

}).call(this);
