// Generated by CoffeeScript 1.4.0
(function() {
  var dev;

  dev = 'AI39si5Us3iYwmRdK0wa2Qf2P9eV-Z8tbjogUWw1B4JQUs\
191PgYNJChEKEooOq6ykQzhywLEBA9WxuKphpWUoCRA7S7jeLi5w';

  module.exports = {
    random: function() {
      var s4;
      s4 = function() {
        return Math.floor(Math.random() * 0x10000).toString(16);
      };
      return s4() + s4() + s4() + s4();
    },
    cookie: function(str) {
      var dict, k, kv, kvs, v, _i, _len;
      dict = {};
      kvs = str.split(';');
      for (_i = 0, _len = kvs.length; _i < _len; _i++) {
        kv = kvs[_i];
        kv = kv.split('=');
        if (!kv[0] || !kv[1]) {
          continue;
        }
        k = kv[0].trim();
        v = kv[1].trim();
        dict[k] = v;
      }
      return dict;
    },
    now: function() {
      return Math.round((new Date()).getTime() / 1000);
    },
    yt: {
      info: function(vidid) {
        return 'http://gdata.youtube.com/feeds/api/videos/' + vidid + '?v=2&alt=json&' + dev;
      }
    }
  };

}).call(this);
